name: plaid_universal
description: Plaid Link for all Flutter official platforms
version: 0.0.1
homepage: https://github.com/maxint-app/plaid_universal

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  alfred: ^1.1.3
  plaid_flutter: ^4.2.0
  flutter_inappwebview: ^6.1.5
  html: ^0.15.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/

platforms:
  android:
  ios:
  macos:
  linux:
  web:
  windows: